### ISSUE TITLE
some question about the paper's result

### ISSUE THREAD

**Issue by AndyYuan96** [CVMI-Lab/ST3D#1]
Hi, thanks for sharing so great work. For the word " We also observe that it is hard to adapt detectors from the point clouds with more LiDAR beams (e.g. Waymo) to the point clouds with fewer LiDAR beams (e.g. NuScenes), while the opposite adaptation is relatively easy" in paper section 4.2, I just think the large improvement on kitti dataset is due to kitti dataset is too small, not about more lidar beams to fewer lidar beams is hard and opposite adaptation is easy,  just recomand that you can give an experiment that nuscene -> waymo' result which is more convincing。

**Comment by jihanyang** [comment]
Hello, thanks for your question. Actually, you can find the results that you want in the apendix.

**Comment by AndyYuan96** [comment]
> Hello, thanks for your question. Actually, you can find the results that you want in the apendix (Table S17).

sorry,I don't notice that.
