### ISSUE TITLE
Segmentation fault when using "nuscenes" eval metric.

### ISSUE THREAD

**Issue by deeptibhegde** [CVMI-Lab/ST3D#10]
When I change the eval metric from "kitti" to "nuscenes" in the config file, after displaying the recall values, it goes to a segmentation fault. I have enabled `--save_to_file`. Below is the error message:

`[2021-07-21 12:34:30,972  eval_utils.py 52  INFO]  *************** EPOCH 18 EVALUATION *****************
eval: 100%|██████████████████████████████| 7033/7033 [56:28<00:00,  2.08it/s, recall_0.3=(119816, 119816) / 202469]
[2021-07-21 13:30:59,219  eval_utils.py 91  INFO]  *************** Performance of EPOCH 18 *****************
[2021-07-21 13:30:59,273  eval_utils.py 93  INFO]  Generate label finished(sec_per_example: 0.1205 second).
[2021-07-21 13:30:59,273  eval_utils.py 109  INFO]  recall_roi_0.3: 0.591775
[2021-07-21 13:30:59,273  eval_utils.py 110  INFO]  recall_rcnn_0.3: 0.591775
[2021-07-21 13:30:59,273  eval_utils.py 109  INFO]  recall_roi_0.5: 0.450168
[2021-07-21 13:30:59,273  eval_utils.py 110  INFO]  recall_rcnn_0.5: 0.450168
[2021-07-21 13:30:59,273  eval_utils.py 109  INFO]  recall_roi_0.7: 0.202480
[2021-07-21 13:30:59,274  eval_utils.py 110  INFO]  recall_rcnn_0.7: 0.202480
[2021-07-21 13:30:59,294  eval_utils.py 118  INFO]  Average predicted number of objects(28130 samples): 22.359
/home/labuser/anaconda3/envs/st3d/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/labuser/anaconda3/envs/st3d/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda-10.2/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/labuser/anaconda3/envs/st3d/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda-10.2/nvvm/libdevice.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
Segmentation fault (core dumped)`

**Comment by jihanyang** [comment]
May I know if you don't enable --save_to_file, whether this error would occur?

**Comment by deeptibhegde** [comment]
I do not get a Segmentation fault but i do get an "killed" message at the same position.

[2021-07-22 00:17:06,493  eval_utils.py 91  INFO]  *************** Performance of EPOCH 18 *****************
[2021-07-22 00:17:06,507  eval_utils.py 93  INFO]  Generate label finished(sec_per_example: 0.1223 second).
[2021-07-22 00:17:06,507  eval_utils.py 109  INFO]  recall_roi_0.3: 0.590574
[2021-07-22 00:17:06,507  eval_utils.py 110  INFO]  recall_rcnn_0.3: 0.590574
[2021-07-22 00:17:06,507  eval_utils.py 109  INFO]  recall_roi_0.5: 0.449422
[2021-07-22 00:17:06,507  eval_utils.py 110  INFO]  recall_rcnn_0.5: 0.449422
[2021-07-22 00:17:06,507  eval_utils.py 109  INFO]  recall_roi_0.7: 0.202070
[2021-07-22 00:17:06,508  eval_utils.py 110  INFO]  recall_rcnn_0.7: 0.202070
[2021-07-22 00:17:06,530  eval_utils.py 118  INFO]  Average predicted number of objects(28130 samples): 22.374
/home/labuser/anaconda3/envs/st3d/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/labuser/anaconda3/envs/st3d/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda-10.2/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/labuser/anaconda3/envs/st3d/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda-10.2/nvvm/libdevice.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
Killed

**Comment by jihanyang** [comment]
I will try it later. This function have been tested before.

**Comment by jihanyang** [comment]
I randomly choose an previous checkpoint and everything goes well. Maybe you need to first locate which code lead to this error, and then I can help you to look for solution.
`
[2021-07-23 13:06:20,639  eval_utils.py 257  INFO]  Average predicted number of objects(6019 samples): 27.334                                                                                               
======                                                                                                                                                                                                      
Loading NuScenes tables for version v1.0-trainval...                                                                                                                                                        
23 category,                                                                                                                                                                                                
8 attribute,                                                                                                                                                                                                
4 visibility,                                                                                                                                                                                               
64386 instance,                                                                                                                                                                                             
12 sensor,                                                                                                                                                                                                  
10200 calibrated_sensor,                                                                                                                                                                                    
2631083 ego_pose,                                                                                                                                                                                           
68 log,                                                                                                                                                                                                     
850 scene,                                                                                                                                                                                                  
34149 sample,                                                                                                                                                                                               
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 52.2 seconds.
======
Reverse indexing ...
Done reverse indexing in 12.8 seconds.
======
[2021-07-23 13:08:33,377  nuscenes_dataset.py 343  INFO]  The predictions of NuScenes have been saved to results_nusc.json
Initializing nuScenes detection evaluation
Loaded results from results_nusc.json. Found detections fo
r 6019 samples.
Loading annotations for val split from nuScenes version: v1.0-trainval
100%|██████████| 6019/6019 [00:13<00:00, 459.60it/s]
Loaded ground truth annotations for 6019 samples.
Filtering predictions
=> Original number of boxes: 164523
=> After distance based filtering: 122856
=> After LIDAR points based filtering: 122856
=> After bike rack filtering: 122856
Filtering ground truth annotations
=> Original number of boxes: 187528
=> After distance based filtering: 134565
=> After LIDAR points based filtering: 121871
=> After bike rack filtering: 121861
Accumulating metric data...
Calculating metrics...
Saving metrics to: /mnt/lustre/yangjihan/OpenPCDet-DA-v3/output/da-waymo-nuscenes_models/secondiou_boxes_length/debug/eval/epoch_30/val/nus_metric/final_result/data
mAP: 0.0488
mATE: 0.9219
mASE: 0.9193
mAOE: 0.9194
mAVE: 1.1230
mAAE: 0.9399
NDS: 0.0543
Eval time: 73.1s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.488   0.219   0.193   0.275   1.984   0.519
truck   0.000   1.000   1.000   1.000   1.000   1.000
bus     0.000   1.000   1.000   1.000   1.000   1.000
trailer 0.000   1.000   1.000   1.000   1.000   1.000
construction_vehicle    0.000   1.000   1.000   1.000   1.000   1.000
pedestrian      0.000   1.000   1.000   1.000   1.000   1.000
motorcycle      0.000   1.000   1.000   1.000   1.000   1.000
bicycle 0.000   1.000   1.000   1.000   1.000   1.000
traffic_cone    0.000   1.000   1.000   nan     nan     nan
barrier 0.000   1.000   1.000   1.000   nan     nan
[2021-07-23 13:10:30,952  eval_utils.py 273  INFO]  ----------------Nuscene detection_cvpr_2019 results-----------------
***car error@trans, scale, orient, vel, attr | AP@0.5, 1.0, 2.0, 4.0
0.22, 0.19, 0.27, 1.98, 0.52 | 39.14, 47.89, 52.57, 55.54 | mean AP: 0.4878450046504619
--------------average performance-------------
trans_err:       0.9219
scale_err:       0.9193
orient_err:      0.9194
vel_err:         1.1230
attr_err:        0.9399
mAP:     0.0488
NDS:     0.0543

[2021-07-23 13:10:30,953  eval_utils.py 280  INFO]  ****************Evaluation done.*****************
`
