### ISSUE TITLE
RCNN regression loss not calculated

### ISSUE THREAD

**Issue by deeptibhegde** [CVMI-Lab/ST3D#11]
Hello,
It is apparent from the code and config files that the rcnn regression loss is not calculated, although the function exists in `roi_head_template.py` . If this is correct, what is the motivation behind this?

**Comment by jihanyang** [comment]
We just aim at regressing IoU score for SECOND and add an roi head. Adding extra rcnn regression loss is actually an potentially strategy to improve performance, but we already have two-stage PVRCNN as a comparsion. Therefore, we just keep SECOND as simple as possible to verify our pipeline works on both one-stage and two-stage architectures.
