### ISSUE TITLE
Config file for Waymo to Nuscenes 

### ISSUE THREAD

**Issue by deeptibhegde** [CVMI-Lab/ST3D#14]
Hello,
Would it be possible to have the config file for the SECOND-iou with Statistical Normalization for the Waymo to Nuscenes scenario?

Thank you

**Comment by jihanyang** [comment]
I will release them later. Since I am struggling into some works, this might need some time. Actually, with the statistic information provided by SN, you can easily reproduce the result of Waymo -> nuScenes just according to the exsiting configs in this repo.

**Comment by jihanyang** [comment]
Already supported.
