### ISSUE TITLE
Support for OpenPCDet v0.3.0

### ISSUE THREAD

**Issue by weijiawang96** [CVMI-Lab/ST3D#15]
Hi, 

I'm very interested in your code. Will you consider supporting OpenPCDet v0.3.0? Seems that my GPU (Nvidia GTX 3080) only supports CUDA 11 for now, and I've been kept having all kinds of issues with running CUDA 9.0 on my computer. It seems that I can only run OpenPCDet v0.3.0 with CUDA 11.

Thank you

**Comment by jihanyang** [comment]
This is one of the thing in my todo list. Actually, in my interval version, I have support v0.3.0. I will support it within a week.

**Comment by jihanyang** [comment]
Supported.
