### ISSUE TITLE
Number of epochs for nuscenes-kitti

### ISSUE THREAD

**Issue by darrenjkt** [CVMI-Lab/ST3D#16]
Hi I was just wondering how many epochs did you train on the nuscenes - kitti baseline (without SN or ROS) to get the result of 17.92 for 3D AP as reported in the paper? I've trained the secondiou_old_anchor.yaml cfg file for 3 epochs (as with ROS and SN) and only got the following results:

Car AP_R40@0.70, 0.70, 0.70:
bbox AP:60.1853, 48.0934, 48.1308
bev  AP:31.2696, 27.1278, 26.6632
3d   AP:4.5068, 3.2667, 3.3441
aos  AP:42.78, 34.73, 35.04

Infos were generated with the original OpenPCDet repo - do I need to regenerate them for KITTI and nuscenes? 

Also I noticed when evaluating the nuscenes-kitti for SN and ROS, they were only trained to 3 epochs. I re-trained the nuscenes dataset with the exact same secondiou_old_anchor_ros.yaml and didn't manage to reproduce the result from the model zoo.  Update: I've re-generated the infos with st3d repo and it gives a lower performance for secondiou_old_anchor_ros.yaml.

Training was done with the command 

```
python train.py --cfg_file cfgs/da-nuscenes-kitti_models/secondiou/secondiou_old_anchor_ros.yaml --batch_size 4 --epochs 3 --extra_tag st3d_infos
```

Cfg file for secondiou_old_anchor_ros.yaml is as below. Dataset_config files were unchanged.
```
CLASS_NAMES: ['car']

DATA_CONFIG:
    _BASE_CONFIG_: cfgs/dataset_configs/da_nuscenes_kitti_dataset.yaml
    MAX_SWEEPS: 1
    PRED_VELOCITY: False
    BALANCED_RESAMPLING: False
    SHIFT_COOR: [0.0, 0.0, 1.8]
    
    DATA_AUGMENTOR:
        DISABLE_AUG_LIST: ['normalize_object_size']
        AUG_CONFIG_LIST:
            - NAME: random_object_scaling
              SCALE_UNIFORM_NOISE: [0.75, 1.0]

            - NAME: normalize_object_size
              SIZE_RES: [-0.75, -0.34, -0.2]

            - NAME: random_world_flip
              ALONG_AXIS_LIST: ['x', 'y']

            - NAME: random_world_rotation
              WORLD_ROT_ANGLE: [-0.3925, 0.3925]

            - NAME: random_world_scaling
              WORLD_SCALE_RANGE: [0.95, 1.05]

DATA_CONFIG_TAR:
    _BASE_CONFIG_: cfgs/dataset_configs/da_kitti_dataset.yaml
    TARGET: True
    FOV_POINTS_ONLY: False
    CLASS_NAMES: ['Car']
    SHIFT_COOR: [0.0, 0.0, 1.6]

MODEL:
    NAME: SECONDNetIoU

    VFE:
        NAME: MeanVFE

    BACKBONE_3D:
        NAME: VoxelBackBone8x

    MAP_TO_BEV:
        NAME: HeightCompression
        NUM_BEV_FEATURES: 256

    BACKBONE_2D:
        NAME: BaseBEVBackbone

        LAYER_NUMS: [5, 5]
        LAYER_STRIDES: [1, 2]
        NUM_FILTERS: [128, 256]
        UPSAMPLE_STRIDES: [1, 2]
        NUM_UPSAMPLE_FILTERS: [256, 256]

    DENSE_HEAD:
        NAME: AnchorHeadSingle
        CLASS_AGNOSTIC: False

        USE_DIRECTION_CLASSIFIER: True
        DIR_OFFSET: 0.78539
        DIR_LIMIT_OFFSET: 0.0
        NUM_DIR_BINS: 2

        ANCHOR_GENERATOR_CONFIG: [
            {
                'class_name': 'car',
                'anchor_sizes': [[4.2, 2.0, 1.6]],
                'anchor_rotations': [0, 1.57],
                'anchor_bottom_heights': [0],
                'align_center': False,
                'feature_map_stride': 8,
                'matched_threshold': 0.55,
                'unmatched_threshold': 0.4
            }
        ]

        TARGET_ASSIGNER_CONFIG:
            NAME: AxisAlignedTargetAssigner
            POS_FRACTION: -1.0
            SAMPLE_SIZE: 512
            NORM_BY_NUM_EXAMPLES: False
            MATCH_HEIGHT: False
            BOX_CODER: ResidualCoder

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 2.0,
                'dir_weight': 0.2,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    ROI_HEAD:
        NAME: SECONDHead
        CLASS_AGNOSTIC: True

        SHARED_FC: [256, 256]
        IOU_FC: [256, 256]
        DP_RATIO: 0.3

        NMS_CONFIG:
            TRAIN:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 9000
                NMS_POST_MAXSIZE: 512
                NMS_THRESH: 0.8
            TEST:
                NMS_TYPE: nms_gpu
                MULTI_CLASSES_NMS: False
                NMS_PRE_MAXSIZE: 1024
                NMS_POST_MAXSIZE: 100
                NMS_THRESH: 0.7

        ROI_GRID_POOL:
            GRID_SIZE: 7
            IN_CHANNEL: 512
            DOWNSAMPLE_RATIO: 8

        TARGET_CONFIG:
            BOX_CODER: ResidualCoder
            ROI_PER_IMAGE: 128
            FG_RATIO: 0.5

            SAMPLE_ROI_BY_EACH_CLASS: True
            CLS_SCORE_TYPE: raw_roi_iou

            CLS_FG_THRESH: 0.75
            CLS_BG_THRESH: 0.25
            CLS_BG_THRESH_LO: 0.1
            HARD_BG_RATIO: 0.8

            REG_FG_THRESH: 0.55

        LOSS_CONFIG:
            IOU_LOSS: BinaryCrossEntropy
            LOSS_WEIGHTS: {
                'rcnn_iou_weight': 1.0,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            }

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
        SCORE_THRESH: 0.1
        OUTPUT_RAW_SCORE: False

        EVAL_METRIC: kitti

        NMS_CONFIG:
            MULTI_CLASSES_NMS: False
            NMS_TYPE: nms_gpu
            NMS_THRESH: 0.01
            NMS_PRE_MAXSIZE: 4096
            NMS_POST_MAXSIZE: 500


OPTIMIZATION:
    OPTIMIZER: adam_onecycle
    LR: 0.003
    WEIGHT_DECAY: 0.01
    MOMENTUM: 0.9

    MOMS: [0.95, 0.85]
    PCT_START: 0.4
    DIV_FACTOR: 10
    DECAY_STEP_LIST: [35, 45]
    LR_DECAY: 0.1
    LR_CLIP: 0.0000001

    LR_WARMUP: False
    WARMUP_EPOCH: 1

    GRAD_NORM_CLIP: 10
``

**Comment by jihanyang** [comment]
Hello, I train it for around 50 epochs. I will revise the config to add this term. Thank you.

**Comment by darrenjkt** [comment]
Hi thanks for your response. 

Just to clarify 50 epochs is for the pre-training of the nuscenes-kitti secondiou_old_anchor.yaml? When I evaluated the model_zoo checkpoint.pth file it says "EPOCH 3 EVALUATION". Also out of curiosity how long does one epoch take for you and what hardware are you using for training? 

According to the OpenPCDet cfg file for [second](https://github.com/open-mmlab/OpenPCDet/blob/c9d31d393acaae34d74cb03bd6ccff9976d3d1f3/tools/cfgs/nuscenes_models/cbgs_second_multihead.yaml#L211)/pointpillars they only train it for 20 epochs (though their model zoo file in evaluation also says something vastly different).

**Comment by jihanyang** [comment]
Hello, you concern is make sense. we decide to use 50 epochs for nus->kitti setting (with over 20,000 frames) since we use 30 epochs for waymo->kitti setting (with over 70,000 frames). Meanwhile, may I know which checkpoint did you used to evaluate? Can you reproduce the result with the checkpoint? The epoch number of two pretrained models for secondiou of nus->kitti should be 33 and 27 separately. Maybe I upload an error checkpoint.

**Comment by darrenjkt** [comment]
If 50 epochs is for nuscenes-kitti pre-trained, how many epochs is for the nusc-kitti st3d training afterwards? Could you also provide that checkpoint in the model zoo?

I downloaded the model ckpt.pth from your model zoo in the nuScenes -> KITTI TASK, first row in the table for SECOND-IoU ROS. I've copied the download link you provided [here](https://drive.google.com/file/d/10mWlQCYGX8gRBpX3GBrqrv1q7z9RG4P3/view?usp=sharing). 

When evaluating the model, this is what I see in the logs. It says EPOCH 3 EVALUATION and hence my confusion. 
![image](https://user-images.githubusercontent.com/39115809/132276663-49574952-5c90-41f5-8263-415e64778823.png)

Regarding reproducing from the checkpoint, that is no issue. I just can't seem to reproduce it when I train it myself to 3 epochs. However, if you're saying that you train the full 28130 nuscenes samples to 50 epochs for this same ckpt.pth then that makes a bit more sense.

**Comment by jihanyang** [comment]
Hello, I guess the epoch 3 is due to this line https://github.com/CVMI-Lab/ST3D/blob/92a647ced6b4f2f2f26ab4e20317658e049c4b68/tools/test.py#L162 with the name `ST3D`. Meanwhile, I download the link and test it, but got:
```
[2021-09-07 14:06:10,520  detector3d_template.py 325  INFO]  ==> Loading parameters from checkpoint ../output/model_zoo/ckpt.pth to GPU
[2021-09-07 14:06:10,713  detector3d_template.py 331  INFO]  ==> Checkpoint trained from version: pcdet+0.2.0+ee0831b+pyab7b158
[2021-09-07 14:06:10,854  detector3d_template.py 350  INFO]  ==> Done (loaded 189/189)
[2021-09-07 14:06:10,864  eval_utils.py 40  INFO]  *************** EPOCH no_number EVALUATION *****************

```
You can try to rename the `ckpt.pth` to `checkpoint_epoch_100.pth`, I guess it will becom epoch 100 evaluation.

The st3d training takes 30 epochs. I will add it to model zoo soon.

**Comment by darrenjkt** [comment]
Thanks for the clarification. Yes please, it'll help with reproducing the results if the epochs are added for all the steps. Appreciate your work.

**Comment by weijiawang96** [comment]
Hi @darrenjkt and @jihanyang, I tried to run the training command like this: 
`python train.py --cfg_file cfgs/da-nuscenes-kitti_models/secondiou/secondiou_old_anchor_ros.yaml --batch_size 1 --epochs 50 --extra_tag st3d_infos`
I'm using batch size = 1, since any number above 1 gives me CUDA out of memory error. Just wish to double check, will setting the batch size to 1 affect the training results? Thx.

**Comment by jihanyang** [comment]
May I know how much the GPU memory that it occupies when `batch_size=1`?

**Comment by weijiawang96** [comment]
Dear @jihanyang,

Thank you so much for your reply. Here's my nvidia-smi when I run batch_size=1:

`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:65:00.0  On |                  N/A |
| 63%   50C    P2   125W / 340W |   6687MiB / 10009MiB |     35%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1447      G   /usr/lib/xorg/Xorg                278MiB |
|    0   N/A  N/A     14852      C   python                           6405MiB |
+-----------------------------------------------------------------------------+`

So the program uses around 63% of my GPU memory. The training loop can run, but I just don't konw if setting batch_size=1 will affect the training results. 

I'm using a single Nvidia GeForce RTX 3080 GPU on my computer.


By the way, here's the CUDA out of memory error when I set bathc_size=4:
Command: 
`python train.py --cfg_file ./cfgs/da-nuscenes-kitti_models/pvrcnn_st3d/pvrcnn_st3d.yaml --batch_size 4 --epochs 50 --extra_tag st3d_infos`

Error (reporting required CUDA memory):
`RuntimeError: CUDA out of memory. Tried to allocate 864.00 MiB (GPU 0; 9.78 GiB total capacity; 7.84 GiB already allocated; 196.12 MiB free; 7.99 GiB reserved in total by PyTorch)`

**Comment by jihanyang** [comment]
Hello, according to the cfg :
https://github.com/CVMI-Lab/ST3D/blob/cce0247ecbb4c9ae6427a5a203647543474c42f9/tools/cfgs/da-nuscenes-kitti_models/pvrcnn_st3d/pvrcnn_st3d.yaml#L217

We use batch size = 2 in defaut, and it seems that GPU memory usage is normal for pvrcnn. All experiments are finished with 1080ti with 11GB GPU memory.

**Comment by weijiawang96** [comment]
Thank you for sharing, seems that I can only train using batch_size = 1 with my current GPU. But strangely, I come across another RecursionError when I ran PVRCNN's command. The command I ran is this:
`python train.py --cfg_file ./cfgs/da-nuscenes-kitti_models/pvrcnn_st3d/pvrcnn_st3d.yaml --batch_size 1 --epochs 50 --extra_tag st3d_infos`

And after 2283 out of 3712 iterations in the train loop, the program stops with this RecursionError:
`RecursionError: maximum recursion depth exceeded while calling a Python object`

it seems these 2 lines of code are called alternatively and indefinitely:
` File "/home/wangweijia/Desktop/UDA/ST3D/tools/../pcdet/datasets/dataset.py", line 253, in prepare_data
    return self.__getitem__(new_index)
  File "/home/wangweijia/Desktop/UDA/ST3D/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 421, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)`

Here's the error:
`[2021-09-29 22:51:14,537  train.py 174  INFO]  **********************Start training cfgs/da-nuscenes-kitti_models/pvrcnn_st3d/pvrcnn_st3d(st3d_infos)**********************
[2021-09-29 22:51:14,935  train_st_utils.py 103  INFO]  ==> Loading pseudo labels from /home/wangweijia/Desktop/UDA/ST3D/output/cfgs/da-nuscenes-kitti_models/pvrcnn_st3d/pvrcnn_st3d/st3d_infos/ps_label/ps_label_e0.pkl
epochs:   0%|                                                                                                                                                                 | 0/50 [00:00<?, ?it/s]
/home/wangweijia/Desktop/UDA/ST3D/tools/../pcdet/models/roi_heads/pvrcnn_head.py:135: UserWarning: This overload of nonzero is deprecated:                                  | 0/3712 [00:00<?, ?it/s]
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  dense_idx = faked_features.nonzero()  # (N, 3) [x_idx, y_idx, z_idx]
generate_ps_e0: 100%|████████████████████████████████████████████████████████████████████████████████████████| 3712/3712 [16:46<00:00,  3.69it/s, pos_ps_box=20.000(20.001), ign_ps_box=0.000(0.001)]
epochs:   0%|                                                                                                          | 0/50 [1:25:13<?, ?it/s, st_loss=2.664(4.211), pos_ps_box=19.8, ign_ps_box=0]
Traceback (most recent call last):█████████████████████████████████████████▎                                       | 2283/3712 [1:07:44<25:31,  1.07s/it, total_it=2283, pos_ps_box=19, ign_ps_box=0]
  File "train.py", line 205, in <module>
    main()
  File "train.py", line 197, in main
    ema_model=None
  File "/home/wangweijia/Desktop/UDA/ST3D/tools/train_utils/train_st_utils.py", line 157, in train_model_st
    dataloader_iter=dataloader_iter, ema_model=ema_model
  File "/home/wangweijia/Desktop/UDA/ST3D/tools/train_utils/train_st_utils.py", line 42, in train_one_epoch_st
    target_batch = next(dataloader_iter)
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RecursionError: Caught RecursionError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  **File "/home/wangweijia/Desktop/UDA/ST3D/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 421, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/home/wangweijia/Desktop/UDA/ST3D/tools/../pcdet/datasets/dataset.py", line 253, in prepare_data
    return self.__getitem__(new_index)**
(Then the above 2 bolded lines repeat for LOTS of times)
File "/home/wangweijia/Desktop/UDA/ST3D/tools/../pcdet/datasets/kitti/kitti_dataset.py", line 421, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/home/wangweijia/Desktop/UDA/ST3D/tools/../pcdet/datasets/dataset.py", line 248, in prepare_data
    data_dict=data_dict
  File "/home/wangweijia/Desktop/UDA/ST3D/tools/../pcdet/datasets/processor/data_processor.py", line 134, in forward
    data_dict = cur_processor(data_dict=data_dict)
  File "/home/wangweijia/Desktop/UDA/ST3D/tools/../pcdet/datasets/processor/data_processor.py", line 74, in transform_points_to_voxels
    voxel_output = voxel_generator.generate(points)
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/spconv/utils/__init__.py", line 258, in generate
    self._height_high_threshold)
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/spconv/utils/__init__.py", line 75, in points_to_voxel
    voxelmap_shape = tuple(np.round(voxelmap_shape).astype(np.int32).tolist())
  File "<__array_function__ internals>", line 6, in round_
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 3637, in round_
    return around(a, decimals=decimals, out=out)
  File "<__array_function__ internals>", line 6, in around
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 3262, in around
    return _wrapfunc(a, 'round', decimals=decimals, out=out)
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
RecursionError: maximum recursion depth exceeded while calling a Python object
`

I'll continue looking into this, but please suggest if you've come across similar issues. By the way, I'm using ST3D's version with OpenPCDet 0.3.

**Comment by jihanyang** [comment]
It seems that some issues dicussed this situation. You can refer to those issues. I have find some errors on ST3D with openpcdet v0.3.0, so I suggest you to re-pull the repo and install it with openpcdet v0.2.0 for reproduction.

**Comment by weijiawang96** [comment]
No problem, thank you!
