### ISSUE TITLE
How to use and visualise the test results

### ISSUE THREAD

**Issue by weijiawang96** [CVMI-Lab/ST3D#18]
Hi Jihan,

I'm very new to this field so please bear with me...

I've tested your code for nuScenes -> KITTI task using SECOND-IoU+ST3D, here is my command: 
`python test.py --cfg_file ./cfgs/da-nuscenes-kitti_models/secondiou_st3d/secondiou_st3d.yaml --batch_size 4 --ckpt ./cfgs/da-nuscenes-kitti_models/secondiou_st3d/ckpt_secondiou_st3d.pth`

And the output is this:
`Car AP@0.70, 0.70, 0.70:
bbox AP:80.3036, 65.9065, 64.7457
bev  AP:78.9386, 65.4960, 64.0457
3d   AP:63.2802, 50.1199, 47.2038
aos  AP:80.08, 65.47, 64.13
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:83.3016, 66.6522, 64.9811
bev  AP:80.5374, 66.3496, 64.2153
3d   AP:62.5984, 48.3767, 45.5974
aos  AP:83.05, 66.16, 64.30
Car AP@0.70, 0.50, 0.50:
bbox AP:80.3036, 65.9065, 64.7457
bev  AP:85.6287, 72.1740, 71.4272
3d   AP:85.3973, 71.3382, 70.1702
aos  AP:80.08, 65.47, 64.13
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:83.3016, 66.6522, 64.9811
bev  AP:87.4123, 73.7019, 72.3442
3d   AP:87.1241, 72.1693, 70.6485
aos  AP:83.05, 66.16, 64.30
`

But I have difficulties in understanding this. I know the results are saved as result.pkl and some logs .txt files, but I really don't know their meanings and how to use them. Also, is there a way to visualise the output, e.g. drawing the predicted & ground truth bounding boxes on the images and LiDAR point clouds?

Sincerely,
Wei

**Comment by weijiawang96** [comment]
Sorry, I will try draw_scenes(points, gt_boxes=None, ref_boxes=None, ref_scores=None, ref_labels=None): in visual_utils.py first. Will reopen if I have further issues.

**Comment by jihanyang** [comment]
Since we use openpcdet as the codebase, our evaluation metrics and visualizations follow it. You can refer to the follow code and issues which might help you.
https://github.com/open-mmlab/OpenPCDet/blob/c9d31d393acaae34d74cb03bd6ccff9976d3d1f3/tools/demo.py#L93

https://github.com/open-mmlab/OpenPCDet/issues/432
