### ISSUE TITLE
When the code will be released?

### ISSUE THREAD

**Issue by canqin001** [CVMI-Lab/ST3D#2]
Hi,

I am very interested to your work. I wonder when you plan to release the main part of the code. Thanks.

Regards,

**Comment by jihanyang** [comment]
Hello,

Thank you for your interesting. Sorry for my late releasing. The code will be released in April or May. I have already organized my code and prepared the pretrained model, but I have struggled in some school's works recently. I need some extra time to write the README and re-check my re-organized code.

**Comment by canqin001** [comment]
Got it. Thanks for your fast reply!

**Comment by xjqi** [comment]
The code is released.
