### ISSUE TITLE
Model pths for ST3D (no SN) on waymo-nuscenes, waymo-kitti

### ISSUE THREAD

**Issue by darrenjkt** [CVMI-Lab/ST3D#20]
Hi Jihan,

Thanks for releasing all your checkpoint files on the model zoo. I'd like to do comparisons with some configurations you've used in your paper. 

Could I get the SECOND-IoU and PV-RCNN pth files for waymo-nuscenes and waymo-kitti specifically with the ST3D (no SN) configuration?

**Comment by jihanyang** [comment]
Sure, I will support them soon. Please stay tuned.

**Comment by jihanyang** [comment]
I already supported these pth files. Nevertheless, due to other works, I haven't checked config files very cautious. If you meet any questiones, feel free to post them here.
