### ISSUE TITLE
Second-IoU or PV-RCNN source only pre-trained models

### ISSUE THREAD

**Issue by weijiawang96** [CVMI-Lab/ST3D#21]
Hi,

Sorry for my trivial question. It seems that I could not find pre-trained .pth models for Second-IoU or PV-RCNN for nuScenes dataset. I'm attempting to reproduce the task nuScenes -> KITTI in Table 1 in ST3D paper, where I wish to see the result of "source only" for Second-IoU or PV-RCNN, both in numerics and visualised graphs. But I can't find the pre-trained .pth files for these 2 methods on nuScenes. 

In this case, do I have to retrain them? It takes ages to retrain on my computer. If you happen to have those .pth files, would you mind upload them? Or, please correct me if they have been uploaded somewhere.

Thanks so much!

**Comment by jihanyang** [comment]
Sure. I will upload them soon. Please stay tuned.

**Comment by weijiawang96** [comment]
Thank you very much! 😊
