### ISSUE TITLE
PVRCNN ST3D (w/ sn) model for Waymo -> KITTI task

### ISSUE THREAD

**Issue by weijiawang96** [CVMI-Lab/ST3D#25]
Dear Jihan,

It seems that the model you linked to PVRCNN ST3D (w/ sn) for Waymo -> KITTI task is actually the model of Second-IoU. When possible, may you please fix that?

Many thanks!! :)

**Comment by jihanyang** [comment]
I will support them latter.

**Comment by jihanyang** [comment]
Done.
