### ISSUE TITLE
About SCALE_UNIFORM_NOISE and SIZE_RES

### ISSUE THREAD

**Issue by weiyithu** [CVMI-Lab/ST3D#26]
Thanks for your great work. How do your determine the hyperparameters SCALE_UNIFORM_NOISE and SIZE_RES? I find they are different in da_nuscenes_dataset.yaml and da_nuscenes_kitti_dataset.yaml. If I want to run a new setting, e.g. KITTI->nuscenes, How should I set these hyperparameters?

**Comment by weiyithu** [comment]
Sorry, I do not get it. I see you use random_object_scaling in [da_nuscenes_dataset](https://github.com/CVMI-Lab/ST3D/blob/master/tools/cfgs/dataset_configs/da_nuscenes_dataset.yaml). If we run KITTI->nuscenes, can you recommand us SCALE_UNIFORM_NOISE and SIZE_RES in da_kitti_nuscenes_dataset.yaml?

**Comment by jihanyang** [comment]
https://github.com/CVMI-Lab/ST3D/blob/023188aabb0cab441d8743c35678383b8e2b1adf/tools/cfgs/dataset_configs/da_nuscenes_dataset.yaml#L22

**Comment by jihanyang** [comment]
Maybe just refer the range of SCALE_UNIFORM_NOISE of nus -> kitti and enlarge the boxes more strong.

**Comment by weiyithu** [comment]
Thanks for your responce.
