### ISSUE TITLE
nuScenes-KITTI PVRCNN ST3D ckpt

### ISSUE THREAD

**Issue by darrenjkt** [CVMI-Lab/ST3D#28]
Hi Jihan,

I downloaded the model ckpt for nuScenes to kitti for pvrcnn st3d and used the same [config](https://github.com/CVMI-Lab/ST3D/blob/master/tools/cfgs/da-nuscenes-kitti_models/pvrcnn_st3d/pvrcnn_st3d.yaml) as provided in this repo. The results I get however are very high (unlike what was reported in the table on the README page of 71.11 R40 AP) which I've pasted below:

```
Car AP@0.70, 0.70, 0.70:
bbox AP:96.6183, 88.7703, 88.4658
bev  AP:88.6752, 87.4535, 87.0203
3d   AP:85.3303, 84.1034, 77.8363
aos  AP:96.47, 88.40, 88.01
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:97.4681, 92.1491, 91.9104
bev  AP:91.8510, 88.8938, 88.6404
3d   AP:86.5975, 83.8631, 81.8083
aos  AP:97.33, 91.73, 91.40
Car AP@0.70, 0.50, 0.50:
bbox AP:96.6183, 88.7703, 88.4658
bev  AP:96.8267, 88.9212, 88.6421
3d   AP:96.8180, 88.9199, 88.6381
aos  AP:96.47, 88.40, 88.01
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:97.4681, 92.1491, 91.9104
bev  AP:97.7262, 94.2243, 92.1346
3d   AP:97.7201, 94.2192, 92.1262
aos  AP:97.33, 91.73, 91.40

```
Could you help me double-check that the uploaded ckpt.pth file for the pvrcnn st3d (no SN) on nuscenes to kitti is correct? Seems like it may be an oracle checkpoint.

**Comment by darrenjkt** [comment]
Hi Jihan, did you manage to double-check the ckpt.pth file?

**Comment by jihanyang** [comment]
Hello, I am really apologize for the late reply. Since we are struggling on CVPR deadline these days, maybe I cannot return to this work until CVPR deadline. Sorry for that.

**Comment by jihanyang** [comment]
Hello,
Sorry for my late reply. I re-test the provided checkpoint, but get similar performance with README page:
```
[2021-11-22 14:58:45,707  eval_utils.py 129  INFO]  Car AP@0.70, 0.70, 0.70:
bbox AP:97.7825, 79.9311, 80.0996
bev  AP:89.0364, 78.6354, 71.1462
3d   AP:85.5135, 68.9282, 68.4336
aos  AP:97.62, 79.42, 79.47
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:98.3705, 78.6531, 78.5923
bev  AP:92.3401, 77.2434, 75.1378
3d   AP:86.8701, 70.2775, 68.1771
aos  AP:98.23, 78.18, 77.99
Car AP@0.70, 0.50, 0.50:
bbox AP:97.7825, 79.9311, 80.0996
bev  AP:97.8597, 80.1740, 80.2094
3d   AP:97.8375, 80.1344, 80.1870
aos  AP:97.62, 79.42, 79.47
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:98.3705, 78.6531, 78.5923
bev  AP:98.4729, 80.9411, 78.7029
3d   AP:98.4609, 80.9132, 78.6830
aos  AP:98.23, 78.18, 77.99

```
May I know whether you also get much higher performance on other uploaded pretrained models?
