### ISSUE TITLE
Config files for NuScenes to KITTI domain adaptation

### ISSUE THREAD

**Issue by deeptibhegde** [CVMI-Lab/ST3D#3]
Hi,
Will you make the DA config files for the NuScenes to KITTI problem available?

Thanks

**Comment by jihanyang** [comment]
Yes, I will make them available, but it will need some time to test them. If you need them urgently, you can email me and I will send them to you.

**Comment by deeptibhegde** [comment]
Emailed, thanks.

**Comment by jihanyang** [comment]
It was miss-classified as spam. I will send them to you soon.

**Comment by jihanyang** [comment]
Already sent.

**Comment by tianweiy** [comment]
Hi @jihanyang  I am also interested in the config. I just sent you an email

**Comment by jihanyang** [comment]
> Hi @jihanyang I am also interested in the config. I just sent you an email

Ok. I will send you soon.

**Comment by Liz66666** [comment]
Hi @jihanyang, I am interested in your great work. Can your also share this config file to me? I just sent you an email. Thanks!

**Comment by jihanyang** [comment]
@Liz66666 Already sent. 
It seems that a lot of researchers are interesting to this setting. I will both support ST3D on latest openpcdet and nus -> kitti config soon.

**Comment by jhzhang19** [comment]
@jihanyang Hi,Thank you for your great work. Can you share the config file of nus->kitti to me? Thanks!

**Comment by jihanyang** [comment]
@jhzhang19 Sure, just send me email.

**Comment by jhzhang19** [comment]
Hello,thank you for your help.Please send me the nus-&gt;kitti config file.Thanks!



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 19, 2021 19:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CVMI-Lab/ST3D] Config files for NuScenes to KITTI domain adaptation (#3)




 
@jhzhang19 Sure, just send me email.
