### ISSUE TITLE
rcnn_iou dimension issue using align_corners=True

### ISSUE THREAD

**Issue by danish87** [CVMI-Lab/ST3D#33]
Thanks for the great work! 
I was able to install all dependencies of ST3D on RTX 3090 using the following guide
[installation_guide_ST3D.txt](https://github.com/CVMI-Lab/ST3D/files/8145297/installation_guide_ST3D.txt)

When I tried to reproduce results using the model provided (model-zoo), 

python3 test.py --cfg_file cfgs/da-nuscenes-kitti_models/secondiou_st3d/secondiou_st3d.yaml --ckpt ../checkpoints/secondiou_st3d_ckpt.pth 

I got the following results
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:83.3016, 66.6522, 64.9811
bev  AP:80.5374, **66.3496**, 64.2153
3d   AP:62.5984, **48.3767**, 45.5974
aos  AP:83.05, 66.16, 64.30

I ran all other models and got accuracies less than what you have mentioned in Table 1.0
After many trials and training even, I got some fixes. The issue is updated PyTorch behavior for the affine grid and grid sampling.
The default behavior up to version 1.2.0 was align_corners = True. After that, the default behavior has been changed to align_corners = False, in order to bring it in line with the default for interpolate().

applying this change in ST3D/pcdet/models/roi_heads/second_head.py

grid = nn.functional.affine_grid(theta,
torch.Size((rois.size(1), spatial_features_2d.size(1), grid_size, grid_size)), align_corners=True)

pooled_features = nn.functional.grid_sample(
spatial_features_2d[b_id].unsqueeze(0).expand(rois.size(1), spatial_features_2d.size(1), height, width),
grid, align_corners=True)

gives me same results as provided in Table 1.0
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:92.6115, 76.7241, 73.1141
bev  AP:90.4426, **77.5308**, 73.3251
3d   AP:71.0224, **55.5878**, 51.2862
aos  AP:92.53, 76.36, 72.59
I am definately able to test provided models.

**Question**
I trained Secondiou + ROS for 80 epochs, training results/losses look fine. However, when i am trying to perform evaluation, i am getting following error
kitti_dataset.py", line 279, in generate_single_sample_dict
    pred_boxes[:, 0:3] -= self.dataset_cfg.SHIFT_COOR # (37, 1, 7)
ValueError: operands could not be broadcast together with shapes (37,1,7) (3,) (37,1,7) 

After debugging and tracing back, I guess I am having a dimension mismatch issue in https://github.com/CVMI-Lab/ST3D/blob/812b64491c3a67a1b578fe46c375fcd0ed2c4305/pcdet/models/roi_heads/second_head.py#L130
rcnn_iou dimension should be torch.Size([1600, 1]) however i am getting torch.Size([1600, 256, 1])

I am trying to debug this issue. I will be glad for any help in this regard

**Comment by jihanyang** [comment]
Hello, I have read your install.txt and guess the reason is existing ST3D cannot be installed on 3090 (not supported with cuda11+) since it bases on openpcdet v0.2. Some previous users also report this problem. Installing with some simply modification to fix cuda error cannot fix this problem. However, our internal version already supported openpcdet v0.3, which can support 3090. I will release it later as another branch. However, due to eccv ddl, it will need some time.

**Comment by danish87** [comment]
I am looking forward to the release of ST3D with openpcdet v0.3 support. 
Kind regards
