### ISSUE TITLE
the difference between scale_ pre_ Object and normalize_ object_size

### ISSUE THREAD

**Issue by csj777** [CVMI-Lab/ST3D#40]
In the file **augmentor_utils.py**, I want to know the difference between **scale_ pre_ Object** and **normalize_ object_size**. In my opinion, they perform the same function。

def scale_pre_object(gt_boxes, points, gt_boxes_mask, scale_perturb, num_try=50):
    """
    uniform sacle object with given range
    Args:
        gt_boxes: (N, 7) under unified coordinates
        points: (M, 3 + C) points in lidar
        gt_boxes_mask: (N), boolen mask for
        scale_perturb:
        num_try:
    Returns:
    """

def normalize_object_size(boxes, points, boxes_mask, size_res):
    """
    :param boxes: (N, 7) under unified boxes
    :param points: (N, 3 + C)
    :param boxes_mask
    :param size_res: (3) [l, w, h]
    :return:
    """

**Comment by jihanyang** [comment]
Please refer to the difference between random object scaling and SN in paper.
