### ISSUE TITLE
Self-training on multiple GPUs with multiple workers does not work

### ISSUE THREAD

**Issue by chreisinger** [CVMI-Lab/ST3D#47]
Hello, 

thank you for your nice work. I adapted your code to v0.5 of OpenPCDet and everything seems to run (only a few result checks done --> sanity checks), except in the scenario when I want to train on multiple GPUs with more than 0 workers. However, single GPU - multiple workers and Multi-GPU - zero workers are no issue. 
The problem is, that when multiple workers get initialised on more than one GPU, the line
https://github.com/CVMI-Lab/ST3D/blob/68a9d3eb0a55c5adbb3d656c6fb597e29ad3155d/pcdet/utils/self_training_utils.py#L233
causes an error. The pseudo label dicts are empty on the worker threads, but not on the main processes of each GPU. This is interesting because the single GPU training with multiple workers runs as expected.

Maybe you already know what could be the problem here. 

Thank you in advance!

**Comment by jihanyang** [comment]
Previous issue already provide solution for this problem.

**Comment by chreisinger** [comment]
Thank you, I must have overseen this one. For all who are interested, the solution can be found here: https://github.com/CVMI-Lab/ST3D/issues/9#issuecomment-893178588
