### ISSUE TITLE
How many point clouds are used when waymo is served as source domain?

### ISSUE THREAD

**Issue by Liz66666** [CVMI-Lab/ST3D#48]
Hi @jihanyang , many thanks for your excellent work. 

According to the config below, 50% of the training frames are used during pre-training. Does this mean that at least about 70,000 frames of waymo point clouds are needed to fully reproduce results of waymo-to-kitti in ST3D paper? Have you tried using 100% or only 20% of the frames?

https://github.com/CVMI-Lab/ST3D/blob/68a9d3eb0a55c5adbb3d656c6fb597e29ad3155d/tools/cfgs/dataset_configs/da_waymo_dataset.yaml#L13-L16

**Comment by jihanyang** [comment]
I am not sure whether we have tried 100% frames since this work have been finished a long time ago. It seems that 20% frames can achieve similar results, but I am also not sure. Maybe it will be better to have a try.
