### ISSUE TITLE
Some question about DSBN

### ISSUE THREAD

**Issue by KevinDuBl** [CVMI-Lab/ST3D#50]
I noticed that, in your ST3D++ paper, the transformation parameters γ and β are shared between two domains since "the transformation parameters γ and β are domain agnostic". but in paper "Domain-specific batch normalization for unsupervised domain adaptation", γ and β are not shared between source domain and target domain. I want to confirm whether the γ and β are shared to reproduce you work. Look forward to you reply, thank you very much!

**Comment by jihanyang** [comment]
No. They are not shared as the explained in this work: https://papers.nips.cc/paper/2019/hash/fd2c5e4680d9a01dba3aada5ece22270-Abstract.html.
BTW, I will support DSNorm and SASD officially soon.

**Comment by KevinDuBl** [comment]
In this paper, it's shared:
![Screenshot from 2022-08-04 17-46-35](https://user-images.githubusercontent.com/20028640/182817569-39195cb9-8bc7-4354-a196-d2af0c0926ba.png)
I'm very puzzled about this.

**Comment by KevinDuBl** [comment]
Well, it's a good news that DSNorm and SASD will release officially, thank you very much!

**Comment by jihanyang** [comment]
Sorry, I should say: they are shared. That's a typo.

**Comment by jihanyang** [comment]
Supported. You can have a try on it. However, as DSNorm and SASD are designed more for small objects such as pedestrian and cyclist. It might not show significant improvment on Car.

**Comment by KevinDuBl** [comment]
You are really a hardworking and enthusiastic man. Thank you very much! Hope you will get good results on NeurIPS 2022!
