### ISSUE TITLE
Config files for multi-class self-training

### ISSUE THREAD

**Issue by zhuoxiao-chen** [CVMI-Lab/ST3D#51]
Hi,

I wonder if the multi-class config (.yaml) files will be available. 

In paper ST3D++: "two thresholds T_pos and T_neg are typically set as 0.6 and 0.25", but it seems that these two thresholds are set for **car** class only. I tried 0.6 and 0.25 for **ped** and **cyc** but the results were not good. 

Could you provide the threshold setting for the other classes? It would be even better if you provide the whole config files for multi-class self-training. 

Thanks.

**Comment by jihanyang** [comment]
On the Waymo -> KITTI, we typically set ped and cyc to 0.2 - 0.55. For other tasks, we have also set it to 0.2-0.5 or 0.1-0.5. We are planning to release of configs after the acceptance as the submission still in revision and the arxiv version is not the final version.

**Comment by zhuoxiao-chen** [comment]
> On the Waymo -> KITTI, we typically set ped and cyc to 0.2 - 0.55. For other tasks, we have also set it to 0.2-0.5 or 0.1-0.5. We are planning to release of configs after the acceptance as the submission still in revision and the arxiv version is not the final version.

Thank you, Jihan. I will have a try.

**Comment by jihanyang** [comment]
It seem that the performance of your pretrained model is kind of low, maybe you can email me and I will send you a config with multi classes.

**Comment by RhythmOfTheRain-Byte** [comment]
> It seem that the performance of your pretrained model is kind of low, maybe you can email me and I will send you a config with multi classes.
Hello jihan, would you please send me a config with multi classes for ST3D++ training. Thank you.
If so, my email is huangyonghui@sjtu.edu.cn .
Thanks very much!
