### ISSUE TITLE
Is the current v0.3 branch actually ST3D++?

### ISSUE THREAD

**Issue by wenyiwangbst** [CVMI-Lab/ST3D#52]
Hi, I just found the current repo which support DSNorm, SASD and HQAC on waymo --> Kitti dataset with second detector. I'm wondering if it means that's actually ST3D++? And also want to ask if we can simply change the detector backbone to other detectors like PVRCNN++?
Thanks again for your awesome work!

**Comment by jihanyang** [comment]
You can refer to changelog.
