### ISSUE TITLE
Some follow up questions! 

### ISSUE THREAD

**Issue by pk1996** [CVMI-Lab/ST3D#53]
Hi! 

Firstly thank you for sharing this great work! 

I wanted to ask a few questions.

1. I wanted to use this repo to do a synthetic to real DA! Do you think it would be possible to reuse this approach for the same? Any insights or leads on this front would be appreciated! 
2. I see you used a multi GPU setup (8?) for the whole pipeline! I haven't gone through the entire code base but would it be even possible to get the pipeline running on a single GPU system (obviously with a reduced batch size)?

Thanks

**Comment by jihanyang** [comment]
1. Sure. I think ST3D can be a solid baseline.
2. We use 4 GPUs by default. We haven't tried single GPU for training. However, I think it can also work with single GPU.

**Comment by pk1996** [comment]
Hey! 
Thanks for your reply!
I will do my share of the investigation! Closing this issue, but will use this in the future for asking such questions!

Thanks
