### ISSUE TITLE
ST3D on CenterPoint

### ISSUE THREAD

**Issue by KevinDuBl** [CVMI-Lab/ST3D#55]
I used random object scaling for domain adaption on waymo->my_dataset on PVRCNN, it works well. I want to use ROS on CenterPoint to alleviate bias of size, but I got worse result than CenterPoint without ROS. Have you ever done some experiments of ST3D on anchor free detection methods? Could you please give me some help on find out the reason for it?

**Comment by jihanyang** [comment]
Sorry, we don't have any attempts on centerpoint. In my perspective, the ROS or SN mainly works for regression head for to help the statsisic bias when estimate the bounding box. In this regard, it should also work for centerpoint. Have you also tried SN?

**Comment by KevinDuBl** [comment]
I tried SN, but get a worse result than without SN! Could you please help me to check the "normalize_object_size" function, thank you very much!
