### ISSUE TITLE
Implementation in mmdetection3d

### ISSUE THREAD

**Issue by Kashu7100** [CVMI-Lab/ST3D#57]
Do you have any plan to implement ST3D/ST3D++ in mmdetection3d?

If not, do you have any advice for me regarding re-implementing this framework in mmdetection3d?

**Comment by jihanyang** [comment]
No. We don't have such plan as MMDet3D is highly integrated. Actually, the ST3D code can be easily decouble from original OpenPCDet. You should take care this function, we apply abs for ignored pseudo labels, whose category id is set to -1.
https://github.com/CVMI-Lab/ST3D/blob/94acba3ccc4718c4fa3a9094a732a92699568d18/pcdet/models/dense_heads/target_assigner/axis_aligned_target_assigner.py#L51-L54

For others, just take care of some functions in dataset for loading pseudo labels.
