### ISSUE TITLE
Question about the implementation of pseudo label update

### ISSUE THREAD

**Issue by s-ryosky** [CVMI-Lab/ST3D#6]
Thank you for releasing your source code.
I have a small question about the implementation of pseudo label update in QTMB.

For what purpose are the pred_cls_scores and the pred_iou_scores  stored in gt_infos?
It looks like they are not used for anything.

https://github.com/CVMI-Lab/ST3D/blob/73dda8c131b960f6970ffd49d44d0f15f6f60f00/pcdet/utils/self_training_utils.py#L189-L194

**Comment by jihanyang** [comment]
Yes. I just use them to try some ideas in my previous attempts, and they are not used in current version.

**Comment by s-ryosky** [comment]
Thank you for your reply. I understood.

I have another question.
It seems that it uses all pseudo labels stored in memory bank for training, including those whose state is ignored.
Is this a bug?
https://github.com/CVMI-Lab/ST3D/blob/73dda8c131b960f6970ffd49d44d0f15f6f60f00/pcdet/datasets/dataset.py#L145-L152
https://github.com/CVMI-Lab/ST3D/blob/73dda8c131b960f6970ffd49d44d0f15f6f60f00/pcdet/models/dense_heads/target_assigner/axis_aligned_target_assigner.py#L38-L51

**Comment by jihanyang** [comment]
No. If I don't store ignored pseudo labels, anchors don't have corresponding GTs will activate negative loss. I set the labels of ignored pseudo labels with negative values, and ignore their losses when calculating loss.

**Comment by s-ryosky** [comment]
I understood it.
I didn't notice that the anchors corresponding to the labels with negative values were trained as negative samples.

Thank you.
