### ISSUE TITLE
train with multiple GPUs

### ISSUE THREAD

**Issue by AGI-player** [CVMI-Lab/ST3D#60]
Hi,

I get some problems in self-training process in st3d++ branch:

1)Perhaps the "consistency_matching" in some yamls should be "consistency_ensemble"

2)When using "tools\cfgs\da-nuscenes-kitti_models\secondiou_st3d\secondiou_st3d++_ros_car.yaml" by running "python train.py --cfg_file xxx" is ok, but I get error "can not find pesudo label for frame:  xxx" by running “sh scripts/dist_train.sh xxx --cfg_file xxx”. The self-training process with multiple GPUs didn't work.

I wonder if someone get the same problems.

Thanks.

**Comment by jihanyang** [comment]
(1) Yes! This is a mistake caused by different name in internal and released version, I will fix it soon. Thank you so much!
(2) Check that whether this issue https://github.com/CVMI-Lab/ST3D/issues/9 can help?

**Comment by AGI-player** [comment]
Thanks for your reply! It works!
