### ISSUE TITLE
experiment results repeat problem

### ISSUE THREAD

**Issue by AGI-player** [CVMI-Lab/ST3D#62]
hi, I run the command "python train.py --cfg_file xxx" in self-training process in st3d++ branch , but the results can not be repeated. Though the random seed seems to  be set in "common_utils.py"，I still get the differernt results every time in the same parameters setting.

**Comment by jihanyang** [comment]
https://github.com/open-mmlab/OpenPCDet/issues/1105

**Comment by AGI-player** [comment]
ok, thanks!
