### ISSUE TITLE
Pseudo labels for training 

### ISSUE THREAD

**Issue by AGI-player** [CVMI-Lab/ST3D#63]
hello,
1) it's my understanding that both the positive state pslabels(pred_labels>0) and the ignored state pslabels(pred_labels<0) are uesd for self training process, why not only using the positive state pslabels for training?
2) in my opinion, it is avaliable for multi-classes, but you noted as follows in dataset.py line 152(st3d++ branch), why?
"only suitable for only one classes, ......"

**Comment by AGI-player** [comment]
for question 1, perhaps due to the code in dataset.py line 153, all the classes(>0 or <0) changed into positive state as follows:
[np.abs(gt_classes.astype(np.int32) - 1]

**Comment by jihanyang** [comment]
1. Please refer to the paper, the ignored state will not activate positive and negative loss. [np.abs(gt_classes.astype(np.int32) - 1] just to assign gt_names for further processing. The loss with negative labels will not be backward in the loss calculation.
2. Just ignore it. It is a comment in the previous version.

**Comment by AGI-player** [comment]
ok, get it, thanks!
