### ISSUE TITLE
pth/yaml files for PointRCNN not present

### ISSUE THREAD

**Issue by adv010** [CVMI-Lab/ST3D#64]
Hi,

I am looking at section 5.3,  ST3D++ which is really detailed and insightful!  There were some comparisons done against MLC-Net/SF-UDA for unsupervised performance , using PointRCNN for nuScenes->KITTI. 

I want to reproduce the same, but PointRCNN pretrained ckpts /yaml files isn't given yet. Is there any plans to release the same?

**Comment by jihanyang** [comment]
Hello, I will update these files soon. Please stay tuned.

**Comment by jihanyang** [comment]
Supported.
