### ISSUE TITLE
Question about loss for ignored boxes

### ISSUE THREAD

**Issue by darrenjkt** [CVMI-Lab/ST3D#66]
Hi Jihan,

In [issue #4 ](https://github.com/CVMI-Lab/ST3D/issues/4#issuecomment-851787719) you said: "We discard negative boxes while make ignored boxes do not contribute to any loss terms." 

Could you reference me the line of code where you ensure ignored boxes do not contribute to any loss terms? 

Thanks

**Comment by jihanyang** [comment]
Here is an example:
https://github.com/CVMI-Lab/ST3D/blob/cf5ece6e43fc7c5801532847d8e96aded6adf202/pcdet/models/dense_heads/anchor_head_template.py#L105-L107
Actually, openpcdet will handle negative label cases without any extra codes. All we need to do is to set the label of ignored boxes to negative.

**Comment by darrenjkt** [comment]
Thanks for that! 

How much of a difference does it make when you use negative class labels? In a fully supervised setting, I could be wrong but I don't think there's any negative labels used when training a detector from scratch.

**Comment by jihanyang** [comment]
About the performance difference, it is studied in the ST3D paper. In the fully supervised setting, no negative labels will be assigned.

**Comment by darrenjkt** [comment]
In Table 3 of your paper you explored ST (w/SN) vs ST (w/ SN) + Triplet. Is that the study you are referring to? 

In the following line of code, it defines negatives as box_cls_labels == 0. The negative cls labels of "Car" that we set which is -1, is [incremented by 1](https://github.com/open-mmlab/OpenPCDet/blob/4713332c5b73b32ac23b425022a06861bfa23b89/pcdet/datasets/dataset.py#L172) which makes cls_label=0 and so it is counted within the negatives. 
https://github.com/CVMI-Lab/ST3D/blob/cf5ece6e43fc7c5801532847d8e96aded6adf202/pcdet/models/dense_heads/anchor_head_template.py#L107

If the cls label of "Car" was set to -2 or if there were other ignored classes e.g. -2,-3,-4, it would lead to the label not be counted as "negatives". How does this affect the training loss?

**Comment by jihanyang** [comment]
Yes.
>In Table 3 of your paper you explored ST (w/SN) vs ST (w/ SN) + Triplet. Is that the study you are referring to?



I recommand you to put a breakpoint here to help you understand the process, your existing understand is not correct.

**Comment by darrenjkt** [comment]
Ok thank you, I'll have to dig a bit deeper
