### ISSUE TITLE
Pretrain on waymo data

### ISSUE THREAD

**Issue by Rody1911641** [CVMI-Lab/ST3D#68]
I have the same problem as [issues41](https://github.com/CVMI-Lab/ST3D/issues/41).I run your code on OpenPCDet 0.6 and SPConv 2.1
I wonder if the cause of this problem is the version problem. Can you give me some advice?

**Comment by jihanyang** [comment]
No. This problem has been fix in current ST3D, which is caused by modifed default setting of grid sampling.

**Comment by Rody1911641** [comment]
Thanks for you!!!
