### ISSUE TITLE
About pretrained weights for ST3D++ - PVRCNN

### ISSUE THREAD

**Issue by adv010** [CVMI-Lab/ST3D#69]
Hey,

I want to crosscheck one point for  Nuscenes -> Kitti on PV-RCNN. Can the [checkpoint](https://connecthkuhk-my.sharepoint.com/personal/jhyang13_connect_hku_hk/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fjhyang13%5Fconnect%5Fhku%5Fhk%2FDocuments%2Fpretrained%5Fmodels%2Fst3d%2B%2B%2Fda%2Dnus%2Dkitti%2Fst3d%2Fpvrcnn) be used as pretrained weights for St3d++ task?

If I understand correctly ST3D++ and ST3D do not differ when pretraining on source, so the same weights should work. Is this correct?

**Comment by jihanyang** [comment]
Yes, they don't have differences on the pretraining stage.
