### ISSUE TITLE
Evaluation on Lyft for paper result

### ISSUE THREAD

**Issue by darrenjkt** [CVMI-Lab/ST3D#70]
Hi Jihan, 

Thanks again for your work. 

I was wondering what configuration did you use for evaluating your self-trained models on the waymo-> Lyft setting in the ST3D paper? In the supplementary you mentioned that Lyft does not annotate vehicles on both sides of the road. What sort of filtering did you apply to evaluate the models on the lyft dataset? 

I noticed the following lines of code in the lyft dataset evaluation but I'm not sure what values you've set to replicate the results.

https://github.com/CVMI-Lab/ST3D/blob/cf5ece6e43fc7c5801532847d8e96aded6adf202/pcdet/datasets/lyft/lyft_dataset.py#L193-L218

**Comment by jihanyang** [comment]
Hello, this part of code is actually not used. I have try to address this issue `Lyft does not annotate vehicles on both sides of the road` in multiple ways, but none of them work well. The evaluation just similar to other datasets without any extra strategies to filter gts or predictions. I just forget to delete this part when release code.

**Comment by darrenjkt** [comment]
I see, thanks for the explanation
