### ISSUE TITLE
Unstable performance

### ISSUE THREAD

**Issue by liuzengyun** [CVMI-Lab/ST3D#72]
Hello, jihan,

It's a great work！

I am learning and reproducing your ST3D++.

But the experimental results show that the performance of the models trained multiple times is different. 

I trained 30 Epochs on KITTI using the model you provided pre-trained by ros on the nuScenes dataset. I used a single 1080Ti.  I used SECOND-IoU Detecter.

This result I reproduced fluctuates a lot, is it normal?

|       **实验**       | **AP3D（Car）↑** | **Epoch** |
| :------------------: | :--------------: | :-------: |
| ST3D++（TPAMI2022+） |      66.01       |     -     |
|    reproduction 1    |  64.80（-1.21）  |   13/30   |
|    reproduction 2    |  64.89（-1.12）  |   21/30   |
|    reproduction 3    |  67.31（+1.3）   |   25/30   |
|    reproduction 4    |  65.08（-0.93）  |   30/30   |
|    reproduction 5    |  63.40（-2.61）  |   27/30   |
|    reproduction 6    |  67.28（+1.27）  |   26/30   |
|    reproduction 7    |  57.16（-8.85）  |   10/30   |

**Comment by jihanyang** [comment]
May I know your batch size? The performance of nuscenes -> KITTI is not very stable due to its sparse point density, but its best performance should be avg+- 2 in most cases. As I typically use 4 gpu and a total batch size 16, I suspect that your case is caused by the smaller batch size.

**Comment by liuzengyun** [comment]
> May I know your batch size? The performance of nuscenes -> KITTI is not very stable due to its sparse point density, but its best performance should be avg+- 2 in most cases. As I typically use 4 gpu and a total batch size 16, I suspect that your case is caused by the smaller batch size.

I used batchsize 4 with a single 1080Ti GPU.

**Comment by jihanyang** [comment]
So, you use 4 times smaller batch size than default setting. I think the unstable could by caused by this change.

**Comment by liuzengyun** [comment]
> So, you use 4 times smaller batch size than default setting. I think the unstable could by caused by this change.

Thank you very much for your answer. I will try it on GPUs with more memory.
