### ISSUE TITLE
AttributeError: 'DataAugmentor' object has no attribute 'random_object_scaling'

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [CVMI-Lab/ST3D#76]
Excuse me， When I perform the training steps, the following error occurs, the yaml file used is
“/tools/cfgs/da-nuscenes-kitti_models/pointrcnn_st3d/pointrcnn_st3d++_car.yaml”
I don't know how to solve this problem, could you help me?
The terminal outputs the following error message

'DataAugmentor' object has no attribute 'random_object_scaling'
File "/home/hyh/OpenPCDet/pcdet/datasets/augmentor/data_augmentor.py", line 24, in init
cur_augmentor = getattr(self.augmentor_configs, cur_cfg.NAME)(config=cur_cfg)
File "/home/hyh/OpenPCDet/pcdet/datasets/dataset.py", line 32, in init
) if self.training else None
File "/home/hyh/OpenPCDet/pcdet/datasets/nuscenes/nuscenes_dataset.py", line 17, in init
dataset_cfg=dataset_cfg, class_names=class_names, training=training, root_path=root_path, logger=logger
File "/home/hyh/OpenPCDet/pcdet/datasets/init.py", line 60, in build_dataloader
logger=logger,
File "/home/hyh/OpenPCDet/tools/train.py", line 120, in main
total_epochs=args.epochs
File "/home/hyh/OpenPCDet/tools/train.py", line 246, in
main()
AttributeError: 'DataAugmentor' object has no attribute 'random_object_scaling'

**Comment by jihanyang** [comment]
Please provide your command. Have you modified any code?

**Comment by RhythmOfTheRain-Byte** [comment]
> 

Thanks very much  for your reply. I didn't modify any code in the project.
The command is  as fellows:
 python tools_st3d/train.py --cfg_file "/home/hyh/OpenPCDet/tools_st3d/cfgs/da-nuscenes-kitti_models/pointrcnn_st3d/pointrcnn_st3d++_car.yaml"

What's more, I run the project based on openpcdet v0.6,and i put the tools folder of the st3d(st3d++) in the project of openpcdet-v0.6. Which replace the location of the original tools folder in openpcdet-v0.6

**Comment by jihanyang** [comment]
I am not sure what you have modified, but you can check whether this function still in 'data_augmentor.py' on your modified version.
https://github.com/CVMI-Lab/ST3D/blob/2634561684dfbafce6ed86e50c6f70f51988593c/pcdet/datasets/augmentor/data_augmentor.py#L59

**Comment by RhythmOfTheRain-Byte** [comment]
> I am not sure what you have modified, but you can check whether this function still in 'data_augmentor.py' on your modified version.
> 
> https://github.com/CVMI-Lab/ST3D/blob/2634561684dfbafce6ed86e50c6f70f51988593c/pcdet/datasets/augmentor/data_augmentor.py#L59

Thank you. I will check it right now!

**Comment by jihanyang** [comment]
These problems are caused by your modification, you remove codes of ST3D, so these problems are caused. You should merge the modification of ST3D to openpcdet v0.6.

**Comment by RhythmOfTheRain-Byte** [comment]
> These problems are caused by your modification, you remove codes of ST3D, so these problems are caused. You should merge the modification of ST3D to openpcdet v0.6.

I'm using  RTX 4090 and can only use the cuda -1.X , so I'd like to try it  with the latest version of pcdet0.6 and spconv2.x. Do you have any suggestions for me！
Thanks anyway！

**Comment by jihanyang** [comment]
I don't think this is a problem for st3d, it should work on 4090 with spconv2.x

**Comment by RhythmOfTheRain-Byte** [comment]
> I don't think this is a problem for st3d, it should work on 4090 with spconv2.x

Ok ，i will try it. Thank you very much.
