### ISSUE TITLE
A question about pre-training model

### ISSUE THREAD

**Issue by jhzhang19** [CVMI-Lab/ST3D#8]
Hello, I have a question for you. For the pre-training model, whether it is possible to add the target data in the pre-train stage, and use the method,such as adversarial training to train the model, so that it has better performance on the target data and can get better pseudo labels. Finally, the model can have better domain adaptability and stability. Do you have any consideration or experiment in this aspect.

**Comment by jihanyang** [comment]
Sure.  It is fully feasible since a lot of 2d methods have verify it, but I don't have any plan to do this.

**Comment by jhzhang19** [comment]
Thank you for your reply!
