### ISSUE TITLE
Performance of Nuscenes2KITTI

### ISSUE THREAD

**Issue by tangtaogo** [CVMI-Lab/ST3D#82]
Thanks for your great work!
I evaluated the provided code and config of **the Nuscenes2KITTI setting**, the performance seems very different from the paper(68.15 / 37.17):
```
bash dist_test.sh 2 --cfg_file cfgs/da-nuscenes-kitti_models/pvrcnn/pvrcnn_old_anchor.yaml  --ckpt pretrained/st3d++/da-nus-kitti/sourceonly/PVRCNN/ckpt.pth --set DATA_CONFIG_TAR.FOV_POINTS_ONLY True
# Car AP_R40@0.70, 0.70, 0.70:
# bev  AP:72.5272, 55.1160, 49.4350
# 3d   AP:38.5542, 27.3954, 24.1336
```
I don't know where the problem lies. I'm using the code from the main branch with **openpcdet=0.4.0 + spconv=cu113**. I just downloaded the KITTI dataset today. 
If it's an environment issue, but when I run the setting for **Waymo2nuscenes**, the results seem similar, although still slightly off (34.50 / 21.47). 
```
bash dist_test.sh 2 --cfg_file cfgs/da-waymo-nus_models/pvrcnn/pvrcnn.yaml --ckpt pretrained/st3d/da-waymo-nus/sourceonly/pvrcnn.pth
# Car AP_R40@0.70, 0.70, 0.70:     
# bev  AP:33.0246, 33.0246, 33.0246
# 3d   AP:20.2057, 20.2057, 20.2057
```

Can you give some advice to solve the problem?
Look forward to your soon reply!

**Comment by jihanyang** [comment]
Hello, thanks for your interesting. May I know whether you just evaluate the provided pretrained models or you train a new model with such results?

**Comment by tangtaogo** [comment]
I just evaluated the provided pretrained models, and the new model I trained also with unsatisfactory results.

**Comment by tangtaogo** [comment]
Moreover, I am also unable to reproduce the result of the Waymo2KITTI setting. It seems like there might be an issue related to the KITTI dataset. Did I miss any specific options?

**Comment by fdy61** [comment]
@tangtaogo Have you worked it out? I have similar questions.
