### ISSUE TITLE
what is the purpose of data augmentation in the target domain?

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [CVMI-Lab/ST3D#85]
Excuse me, sorry to bother you. 
I'd like to ask, during the training process of the second stage, what is the purpose of data augmentation in the target domain, and when does it take effect?  Because, as far as I know,the labels for target domain data are obtained based on pseudo-labels.
Thank you!
As in the config file: pointrcnn_st3d++_car.yaml

DATA_CONFIG_TAR:
    # _BASE_CONFIG_: cfgs/dataset_configs/da_kitti_dataset.yaml
    _BASE_CONFIG_: tools_st3d/cfgs/dataset_configs/da_nuscenes_kitti_dataset.yaml
    TARGET: True
    FOV_POINTS_ONLY: True
    USE_PSEUDO_LABEL: True
    # CLASS_NAMES: ['Car']
    CLASS_NAMES: ['car']
    SHIFT_COOR: [0.0, 0.0, 1.6]

    DATA_PROCESSOR:
        -   NAME: mask_points_and_boxes_outside_range
            REMOVE_OUTSIDE_BOXES: True

        -   NAME: sample_points
            NUM_POINTS: {
                'train': 32768,
                'test': 32768
            }

        -   NAME: shuffle_points
            SHUFFLE_ENABLED: {
                'train': True,
                'test': False
            }

    DATA_AUGMENTOR:
        DISABLE_AUG_LIST: [ 'placeholder' ]
        AUG_CONFIG_LIST:
            - NAME: random_object_scaling
              SCALE_UNIFORM_NOISE: [ 0.9, 1.1 ]

            - NAME: random_object_rotation
              ROT_PROB: 1.0
              ROT_UNIFORM_NOISE: [ -0.78539816, 0.78539816 ]

            - NAME: random_world_flip
              ALONG_AXIS_LIST: [ 'x', 'y' ]

            - NAME: random_world_rotation
              WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

            - NAME: random_world_scaling
              WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

**Comment by jihanyang** [comment]
Hi, the short answer is data augmentation can avoid overfitting. I think the CDA module and its corresponding ablation study in the ST3D paper might answer this question.

**Comment by jihanyang** [comment]
Yes, data augmentation can be any form for target data, and using ROS or not in the target domain will not matter a lot.

**Comment by RhythmOfTheRain-Byte** [comment]
> Yes, data augmentation can be any form for target data, and using ROS or not in the target domain will not matter a lot.

OK,Thank you for your response. Best wishes!
